---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
tasks:
  create:
    summary: Create the k3d Development Bundle
    desc: Create the K3d Development Bundle
    dir: bundle
    cmds:
      - uds create . --confirm --no-progress
    silent: true
  deploy:
    summary: Deploy the K3d Development Bundle
    desc: Deploy the K3d Development Bundle
    deps: ['create']
    dir: bundle
    cmds:
      - |
        echo "Deploying the K3d Development Bundle..."
        BUNDLE_VERSION=$(ls uds-bundle-k3d-development-* 2>/dev/null | sort -V | tail -n 1)
        if [ -z "$BUNDLE_VERSION" ]; then
          echo "Error: No bundle version found."
          exit 1
        fi
        uds deploy "$BUNDLE_VERSION" --confirm --no-progress
        echo "Deployment of $BUNDLE_VERSION completed."
