---
replicas: 1
mode: standalone

resources:
  requests:
    memory: 256Mi
    cpu: 150m
persistence:
  size: 50Gi

buckets:
  - name: forge

# forge test user
users:
  - accessKey: forge
    secretKey: forge-secret
    policy: readwrite-username-policy

policies:
  - name: readwrite-username-policy
    statements:
      - effect: Allow # this is the default
        resources:
          - "arn:aws:s3:::${aws:username}*/*"
        actions:
          - "s3:AbortMultipartUpload"
          - "s3:GetObject"
          - "s3:DeleteObject"
          - "s3:PutObject"
          - "s3:ListMultipartUploadParts"
      - resources:
          - "arn:aws:s3:::${aws:username}*"
        actions:
          - "s3:CreateBucket"
          - "s3:DeleteBucket"
          - "s3:GetBucketLocation"
          - "s3:ListBucket"
          - "s3:ListBucketMultipartUploads"

postJob:
  podAnnotations:
    sidecar.istio.io/inject: "false"
