---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  tools: .taskfiles/Tools/Taskfile.yaml
  bundle: .taskfiles/Bundle/Taskfile.yaml
  pre-commit:
    aliases: ["pre"]
    taskfile: .taskfiles/PreCommit/Taskfile.yaml
tasks:
  default:
    desc: Show help
    cmds:
      - task --list
  create:
    desc: Create local Zarf Package for Testing
    cmds:
      - zarf package create . --confirm --no-progress
  setup:
    summary: Setup Developer Environment
    desc: Setup Development Environment
    deps:
      - tools:docker
      - create
    cmds:
      - task bundle:deploy-k3d-development-bundle

  clean:
    summary: Clean Developer Environment
    desc: Clean Development Environment
    cmds:
      - task tools:k3d-remove

  nuke:
    summary: Removed all Artifacts and Deletes the k3d Cluster
    cmds:
      - task -p tools:k3d-remove tools:clean
      - zarf tools clear-cache
