---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  CLUSTER:
    sh: |
      k3d cluster list --no-headers | awk '{print $1}'
  VERSION:
    sh: |
      find . -name 'zarf-package-k3d-*' | \
      awk -F'zarf-package-k3d-' '{print $2}' | \
      awk -F'.tar.zst' '{print $1}' | \
      head -n 1

includes:
  kubernetes: .taskfiles/Kubernetes/Taskfile.yaml
  tools: .taskfiles/Tools/Taskfile.yaml
  bundle: .taskfiles/Bundle/Taskfile.yaml
  pre-commit:
    aliases: ["pre"]
    taskfile: .taskfiles/PreCommit/Taskfile.yaml

tasks:
  default:
    desc: Show help
    cmds:
      - task --list

  create:
    desc: "Create local Zarf Package"
    cmds:
      - zarf package create . --confirm --no-progress --skip-sbom

  setup:
    summary: Setup Developer Environment
    desc: Setup Development Environment
    deps:
      - tools:docker.start
      - create
    cmds:
      - task bundle:deploy-k3d-development-bundle

  clean:
    summary: Clean Developer Environment
    desc: Clean Development Environment
    cmds:
      - task tools:k3d-remove
      - rm -f zarf-package-k3d-{{.VERSION}}.tar.zst
    requires:
      vars:
        - VERSION

  nuke:
    summary: Remove all Artifacts and Delete the k3d Cluster
    cmds:
      - task -p tools:k3d-remove
      - zarf tools clear-cache
