---
options:
  log_level: debug
  no_progress: false
  oci_concurrency: 3
variables:
  k3d:
    cluster_name: dev
    domain: .*\\.demo\\.dev
    k3s_image: ghcr.io/beholdenkey/oss/forge-k3d-k3s:v1.30.0-k3s1
