---
name: Prune Container Registry

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  prune-ghcr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prune GHCR Versions
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: beholdenkey
          container: packages/k3d
          dry-run: false
          keep-last: 2
          prune-untagged: true
